name: defend_the_donut
description: >
  Everyone knows donuts are the most precious things in the Universe.
  However, our despicable enemies from the Empire are seeking to destroy such a beloved treasure.
  It's up to you to defend your donut from the Empire's ships.
  How long can you keep up?
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-279.2.beta <4.0.0'

dependencies:
  flame: ^1.16.0
  flame_audio: ^2.10.0
  flame_3d: ^0.1.0-dev.1
  flutter:
    sdk: flutter
  pointer_lock:
    git:
      url: https://github.com/helgoboss/pointer_lock.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/sfx/
    - assets/objects/donuts/
    - assets/objects/ships/

  fonts:
    - family: SingleDay
      fonts:
        - asset: assets/fonts/SingleDay-Regular.ttf
